# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Actions"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

permissions: {}  # yamllint disable-line rule:braces

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    actionlint:
        name: "Actionlint"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Run actionlint"
            uses: "docker://rhysd/actionlint:latest"
            with:
                args: "-color -verbose -shellcheck ''"
