# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrity"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

permissions: {}  # yamllint disable-line rule:braces

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    call_workflow_integrity:
        name: "Integrity"
        uses: "szepeviktor/byte-level-care/.github/workflows/reusable-integrity.yml@master"
        with:
            executables: >-
                deploy-receiver.sh
            not-printable-ascii-paths: >-
                public/
            export-excludes: >-
                --exclude="*.*"
                --exclude="public" --exclude="public/*"
            exported-paths: >-
                LICENSE
